name: Screen Reader Accessibility Audit

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, windows, nvda-windows]
    steps:
      - name: Confirm we're on the right box
        shell: pwsh
        run: |
          Write-Host "Running on: $env:COMPUTERNAME"
          Write-Host "As user: $env:USERNAME"
          Write-Host "Working directory: $PWD"